refractoring of ladders and problems
Code-dig-ger/Frontend pull request #23
Opened 2021-10-17 15:45 UTC by sanyamjain036

fix #5

2021-10-18 06:58 UTC, Anurag5086 requested changes

2021-10-18 06:58 UTC, Anurag5086 commented on src/actions/auth.actions.js
>      return fetch('https://api.codedigger.tech/auth/login/',{
We always use await in an async function.

2021-10-18 06:58 UTC, Anurag5086 commented on src/actions/auth.actions.js
>      return fetch('https://api.codedigger.tech/auth/login/',{
```suggestion
    return await fetch('https://api.codedigger.tech/auth/login/',{
```

2021-10-18 06:58 UTC, Anurag5086 commented on src/actions/auth.actions.js
>      return fetch(`https://api.codedigger.tech/auth/register/?redirect_url=${process.env.REACT_APP_SEND_EMAIL_RDURL}`,{
Add await here as well and in every async function below.

2021-10-18 06:58 UTC, Anurag5086 commented on src/actions/lists.actions.js
> +export async function getThisList(acc,wise,type,slug){
change `acc` parameter to `accessToken`. Make this change everywhere you find.

2021-10-18 06:58 UTC, Anurag5086 commented on src/actions/mentors.actions.js
> +export async function removeMentor(acc,mName){
change `mName` to `mentorName`

2021-10-18 06:58 UTC, Anurag5086 commented on src/actions/mentors.actions.js
> +export async function addmentor(acc,guru){
Change `guru` to `mentorName` here as well.

2021-10-18 06:58 UTC, Anurag5086 commented on src/actions/problems.actions.js
> +export async function getProblemsWithCreds(queryStr,acc){
Change `queryStr` to `queryString` and `acc` to `accessToken`.

2021-10-18 06:58 UTC, Anurag5086 commented on src/actions/profile.actions.js.js
> +export async function getProfile(acc,handle){
change `handle` to `userHandle`.

2021-10-18 06:58 UTC, Anurag5086 commented on src/components/ProblemLadderCard.js
>                    <h6 style={{color:"#d9d9d9"}}>{props.wise1}</h6>
Remove all inline css. Add to a new styles.css file.

2021-10-18 06:58 UTC, Anurag5086 commented on src/pages/ladders/LaddersLevel.js
> +    const [dat, setDat] = useState([]);
Rename this to make to more understandable.

2021-10-18 07:50 UTC, saikeshari requested changes

2021-10-18 07:50 UTC, saikeshari commented on src/pages/ladders/LaddersLevel.js
> +                                    key={index}
See if you can combine the two ProblemLadderCards removing the if-else
Try such that pass first_time as parameter with value null when its not available and its value when it is available.
Then check in ProblemLadderCard that if first_time is null, return acc to practice else work acc to ladder.

2021-10-24 07:59 UTC, sanyamjain036 commented on src/actions/mentors.actions.js
> +export async function addmentor(acc,guru){
but mName is mentorName

2021-10-24 08:02 UTC, Anurag5086 commented on src/actions/mentors.actions.js
> +export async function addmentor(acc,guru){
guru itself is mentor

2021-10-24 08:15 UTC, sanyamjain036 commented on src/actions/mentors.actions.js
> +export async function addmentor(acc,guru){
okk , so, do I have to change mName and guru to mentorName?

2021-10-24 08:32 UTC, Anurag5086 commented on src/actions/mentors.actions.js
> +export async function addmentor(acc,guru){
Yes

2021-10-25 09:56 UTC, Anurag5086 approved these changes
LGTM! 👍

2021-10-25 09:58 UTC, Anurag5086 commented
@Jeevier There is a conflicting file `src/pages/ladders/LaddersLevel.js`. Try to resolve this conflict.

2021-10-25 10:06 UTC, saikeshari commented
Pull the latest code and you will see conflicts @Jeevier .
I have put comments and removed some unused code, Look into and try to resolve.

2021-10-26 17:32 UTC, saikeshari approved these changes

2021-10-26 17:32 UTC, merged