Refactoring Problem Page and Contest Page
Code-dig-ger/Frontend pull request #26
Opened 2021-10-24 13:19 UTC by ashank2603

2021-10-24 19:13 UTC, Anurag5086 requested changes
Remove unnecessary comments.

2021-10-24 19:13 UTC, Anurag5086 commented on public/index.html
> +    <title>CODEDIGGER (local)</title>
Change this back to `CODEDIGGER`

2021-10-24 19:13 UTC, Anurag5086 commented on src/pages/contestsPage/ContestPage.js
> +// const AntSwitch = withStyles((theme) => ({
Remove the comments, if not required.

2021-10-24 19:13 UTC, Anurag5086 commented on src/pages/problemsPage/ProblemsPage.js
> +                    // style={{
Remove the comments.

2021-10-24 19:13 UTC, Anurag5086 commented on src/pages/problemsPage/ProblemsPage.js
> +                                    <input onChange={(e)=>setSearchText(e.target.value)} type="search" id="form1" class="form-control" style={{height:'3rem', width:'26rem'}} placeholder="Search" />
Remove inline css.

2021-11-02 14:22 UTC, saikeshari approved these changes

2021-11-02 15:26 UTC, Anurag5086 commented
@ashank2603 Please resolve the conflicts.

2021-11-07 14:02 UTC, merged